In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','placed'])
df.head()

   cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [ ]:
def initialize_Parameters(layers_dim):
  np.random.seed(3)
  parameters={}
  L=len(layers_dim)
  for l in range(1,L):
    parameters['W'+str(l)]=np.ones((layers_dim[l-1],layers_dim[l]))*0.1
    parameters['b'+str(l)]=np.zeros((layers_dim[l],1))
  return parameters

In [ ]:
# utility functions
def sigmoid(Z):
  A=1/(1+np.exp(-Z))
  return A

In [ ]:
def linear_forward(A_prev,W,b):
  Z=np.dot(W.T,A_prev)+b
  A=sigmoid(Z)
  return A

In [ ]:
def L_layer_forward(X,parameters):
  A=X
  L=len(parameters)//2
  for l in range(1,L+1):
    A_prev=A
    W1=parameters['W'+str(l)]
    b1=parameters['b'+str(l)]
    A=linear_forward(A_prev,W1,b1)
  return A,A_prev

In [ ]:
initialize_Parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [ ]:
def update_parameters(parameters,y,y_hat,learning_rate,A1,X):
  parameters['W2'][0][0]=parameters['W2'][0][0]+(learning_rate*(y-y_hat)*A1[0][0])
  parameters['W2'][1][0]=parameters['W2'][1][0]+(learning_rate*(y-y_hat)*A1[1][0])
  parameters['b2'][0][0]=parameters['b2'][0][0]+(learning_rate*(y-y_hat))

  parameters['W1'][0][0]=parameters['W1'][0][0]+(learning_rate*(y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1]=parameters['W1'][0][1]+(learning_rate*(y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0]=parameters['b1'][0][0]+(learning_rate*(y-y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0]=parameters['W1'][1][0]+(learning_rate*(y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1]=parameters['W1'][1][1]+(learning_rate*(y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0]=parameters['b1'][1][0]+(learning_rate*(y-y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))
  return parameters

In [ ]:
# epochs implementation
params=initialize_Parameters([2,2,1])
epochs=50
for i in range(epochs):
  loss=[]
  for j in range(df.shape[0]):
    x=df[['cgpa','profile_score']].values[j].reshape(2,1)
    y=df[['placed']].values[j][0]
    y_hat,A1=L_layer_forward(x,params)
    y_hat=y_hat[0]

    update_parameters(params,y.item(),y_hat.item(),0.001,A1,x)
    loss.append(-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))
  print('Epoch - ',i+1,'Loss-',np.array(loss).mean())
params

Epoch -  1 Loss- 0.6941717414861723
Epoch -  2 Loss- 0.6941618840080915
Epoch -  3 Loss- 0.6941520705403675
Epoch -  4 Loss- 0.6941423008716868
Epoch -  5 Loss- 0.6941325747917801
Epoch -  6 Loss- 0.6941228920914183
Epoch -  7 Loss- 0.694113252562406
Epoch -  8 Loss- 0.6941036559975762
Epoch -  9 Loss- 0.6940941021907857
Epoch -  10 Loss- 0.694084590936909
Epoch -  11 Loss- 0.6940751220318339
Epoch -  12 Loss- 0.6940656952724554
Epoch -  13 Loss- 0.6940563104566712
Epoch -  14 Loss- 0.694046967383376
Epoch -  15 Loss- 0.6940376658524566
Epoch -  16 Loss- 0.694028405664787
Epoch -  17 Loss- 0.694019186622223
Epoch -  18 Loss- 0.6940100085275969
Epoch -  19 Loss- 0.694000871184713
Epoch -  20 Loss- 0.6939917743983431
Epoch -  21 Loss- 0.6939827179742198
Epoch -  22 Loss- 0.693973701719033
Epoch -  23 Loss- 0.6939647254404246
Epoch -  24 Loss- 0.6939557889469835
Epoch -  25 Loss- 0.6939468920482408
Epoch -  26 Loss- 0.693938034554665
Epoch -  27 Loss- 0.6939292162776569
Epoch -  28 Loss- 0.6939204370295454
Epoch -  29 Loss- 0.6939116966235824
Epoch -  30 Loss- 0.6939029948739378
Epoch -  31 Loss- 0.6938943315956949
Epoch -  32 Loss- 0.6938857066048463
Epoch -  33 Loss- 0.6938771197182885
Epoch -  34 Loss- 0.6938685707538178
Epoch -  35 Loss- 0.693860059530125
Epoch -  36 Loss- 0.6938515858667921
Epoch -  37 Loss- 0.6938431495842858
Epoch -  38 Loss- 0.6938347505039549
Epoch -  39 Loss- 0.6938263884480249
Epoch -  40 Loss- 0.6938180632395932
Epoch -  41 Loss- 0.6938097747026254
Epoch -  42 Loss- 0.6938015226619503
Epoch -  43 Loss- 0.6937933069432554
Epoch -  44 Loss- 0.6937851273730834
Epoch -  45 Loss- 0.6937769837788271
Epoch -  46 Loss- 0.6937688759887246
Epoch -  47 Loss- 0.6937608038318563
Epoch -  48 Loss- 0.6937527671381389
Epoch -  49 Loss- 0.6937447657383236
Epoch -  50 Loss- 0.6937367994639887

{'W1': array([[0.09995316, 0.0991031 ],
        [0.09995955, 0.09910591]]),
 'b1': array([[-0.00025234],
        [-0.00025216]]),
 'W2': array([[0.09624378],
        [0.09624801]]),
 'b2': array([[-0.00775436]])}

# Keras

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df=pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','placed'])
df.head()

   cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model=Sequential()
model.add(Dense(2,activation='sigmoid',input_dim=2))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[ 0.6926844 , -0.4784487 ],
        [ 0.24895906,  1.0604476 ]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[1.2561766],
        [0.9525336]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weights=[np.array([[0.1,0.1],[0.1,0.1]],dtype=np.float32),np.array([0.,0.],dtype=np.float32),np.array([[0.1],[0.1]],dtype=np.float32),np.array([0.],dtype=np.float32)]

In [ ]:
model.set_weights(new_weights)

In [ ]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="binary_crossentropy",optimizer=optimizer)

In [ ]:
model.fit(df.iloc[:,:-1].values,df['placed'].values,epochs=50,verbose=1,batch_size=1)

Epoch 1/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 0.6950
Epoch 2/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6939
Epoch 3/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6941
Epoch 4/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.6937
Epoch 5/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6939
Epoch 6/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6938
Epoch 7/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6938
Epoch 8/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6937
Epoch 9/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6936
Epoch 10/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6936
Epoch 11/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6937
Epoch 12/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6936
Epoch 13/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6935
Epoch 14/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6937
Epoch 15/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6936
Epoch 16/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6936
Epoch 17/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6934
Epoch 18/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6935
Epoch 19/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6935
Epoch 20/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6934
Epoch 21/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6934
Epoch 22/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6934
Epoch 23/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6934
Epoch 24/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6933
Epoch 25/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6933
Epoch 26/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6933
Epoch 27/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6934
Epoch 28/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6932
Epoch 29/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6933
Epoch 30/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6932
Epoch 31/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6934
Epoch 32/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6932
Epoch 33/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6931
Epoch 34/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6932
Epoch 35/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6932
Epoch 36/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6931
Epoch 37/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6931
Epoch 38/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6931
Epoch 39/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6933
Epoch 40/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6931
Epoch 41/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6930
Epoch 42/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6932
Epoch 43/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.6930
Epoch 44/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6930
Epoch 45/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6930
Epoch 46/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6929
Epoch 47/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.6931
Epoch 48/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6931
Epoch 49/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6929
Epoch 50/50
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.6929